gave up

diff --git a/.github/workflows/create_release_branch.yml b/.github/workflows/create_release_branch.yml
--- a/.github/workflows/create_release_branch.yml
+++ b/.github/workflows/create_release_branch.yml
@@ -84,48 +84,48 @@ jobs:
           gh workflow run release_container_apps_infra.yml \
             --ref $NEW_BRANCH_NAME
 
-      - name: Waiting for workflows to be ready
-        run: sleep 15s
-        shell: bash
+      # - name: Waiting for workflows to be ready
+      #   run: sleep 15s
+      #   shell: bash
 
-      - name: Waiting for infra workflows to complete..
-        run: |
-          GITHUB_REPOSITORY=pagopa
+      # - name: Waiting for infra workflows to complete..
+      #   run: |
+      #     GITHUB_REPOSITORY=pagopa
           
-          run_ids=$(gh run list -b $NEW_BRANCH_NAME -s waiting --json databaseId | jq -r 'sort_by(.created_at) | reverse | .[].databaseId')
-          echo "run ids: \n$run_ids"
+      #     run_ids=$(gh run list -b $NEW_BRANCH_NAME -s waiting --json databaseId | jq -r 'sort_by(.created_at) | reverse | .[].databaseId')
+      #     echo "run ids: \n$run_ids"
 
-          for run_id in $run_ids; do
+      #     for run_id in $run_ids; do
           
-            job_status=$(gh api repos/$GITHUB_REPOSITORY/actions/runs/$run_id/jobs --json jobs[]."name" --jq '.[]' | grep -i 'uat' | xargs -I{} gh api repos/$GITHUB_REPOSITORY/actions/jobs/{}/steps --json status --jq '.[0]')
+      #       job_status=$(gh api repos/$GITHUB_REPOSITORY/actions/runs/$run_id/jobs --json jobs[]."name" --jq '.[]' | grep -i 'uat' | xargs -I{} gh api repos/$GITHUB_REPOSITORY/actions/jobs/{}/steps --json status --jq '.[0]')
             
-            while true; do
-              if [ "$job_status" == "completed" ] || [ "$job_status" == "failure" ] || [ "$job_status" == "success" ]; then
-                  break
-              fi
-              sleep 10
-            done
+      #       while true; do
+      #         if [ "$job_status" == "completed" ] || [ "$job_status" == "failure" ] || [ "$job_status" == "success" ]; then
+      #           break
+      #         fi
+      #         sleep 10
+      #       done
 
-            if [ "$job_status" == "failure" ]; then
-              echo "Job with 'uat' in the name failed."
-              exit 1
-            fi
-          done
+      #       if [ "$job_status" == "failure" ]; then
+      #         echo "Job failed."
+      #         exit 1
+      #       fi
+      #     done
 
-          # while true; do
-          #   for run_id in $run_ids; do
-          #     job_status=$(gh api repos/pagopa/selfcare-onboarding/actions/runs/$run_id/jobs --json jobs[\"$JOB_NAME\"].status --jq '.[0]')
-          #     if [ "$job_status" == "completed" ] || [ "$job_status" == "failure" ] || [ "$job_status" == "success" ]; then
-          #         break
-          #     fi
-          #   sleep 5
-          # done
+      #     # while true; do
+      #     #   for run_id in $run_ids; do
+      #     #     job_status=$(gh api repos/pagopa/selfcare-onboarding/actions/runs/$run_id/jobs --json jobs[\"$JOB_NAME\"].status --jq '.[0]')
+      #     #     if [ "$job_status" == "completed" ] || [ "$job_status" == "failure" ] || [ "$job_status" == "success" ]; then
+      #     #         break
+      #     #     fi
+      #     #   sleep 5
+      #     # done
           
-          # for run_id in $run_ids; do
-          #   gh run watch $run_id \
-          #     --interval 5 \
-          #     --exit-status
-          # done
+      #     # for run_id in $run_ids; do
+      #     #   gh run watch $run_id \
+      #     #     --interval 5 \
+      #     #     --exit-status
+      #     # done
 
       - name: Trigger Functions UAT Release
         run: |
@@ -137,12 +137,12 @@ jobs:
           gh workflow run release_ms.yml \
             --ref $NEW_BRANCH_NAME
 
-      - name: Waiting for workflows to complete..
-        run: |
-          workflows_ids=$(gh workflow list --json name,id | jq -r 'map(select(.name | test("(?i)deploy"))) | .[].id')
+      # - name: Waiting for workflows to complete..
+      #   run: |
+      #     workflows_ids=$(gh workflow list --json name,id | jq -r 'map(select(.name | test("(?i)deploy"))) | .[].id')
 
-          for id in $workflows_ids; do
-            gh run watch $id \
-              --interval 5 \
-              --exit-status
-          done
+      #     for id in $workflows_ids; do
+      #       gh run watch $id \
+      #         --interval 5 \
+      #         --exit-status
+      #     done
